# Generated by Django 4.2.5 on 2023-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_line', models.CharField(max_length=16, verbose_name='Верхняя стока')),
                ('center_line', models.CharField(max_length=16, verbose_name='Центральная стока')),
                ('bottom_line', models.CharField(max_length=16, verbose_name='Нижняя стока')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, unique=True, verbose_name='Название')),
                ('url', models.CharField(max_length=128, unique=True, verbose_name='url')),
                ('serial_number', models.IntegerField(max_length=2, unique=True, verbose_name='Порядковый номер')),
            ],
        ),
    ]
